name: breun
permalink: /:year/:month/:title.html
exclude: ['README.md', 'deploy']
url: https://breun.nl
twitter:
  consumer_key: TODO
  consumer_secret: TODO
  access_token: TODO
  access_token_secret: TODO
