#!/bin/sh
# https://github.com/envygeeks/jekyll-docker
# https://hub.docker.com/r/jekyll/jekyll/tags/

#JEKYLL_VERSION=4.2.2
#docker run --platform linux/amd64 --rm  --volume="$PWD:/srv/jekyll" -it -p 127.0.0.1:4000:4000 jekyll/minimal:$JEKYLL_VERSION
#docker run --platform linux/amd64 --rm --volume="$PWD:/srv/jekyll" -it jekyll/minimal:$JEKYLL_VERSION jekyll build

#jekyll serve
jekyll build