baseURL = "https://breun.nl/"
title = "breun"
locale = "en-US"
uglyURLs = true

# Disable unused page kinds
disableKinds = ["taxonomy", "term"]

[security]
# https://gohugo.io/configuration/security/#allowcontent
allowContent = ["^text/markdown$", "^text/html$"]

# Extract date from filename if missing from front matter
[frontmatter]
date = [":filename", "date", "publishDate"]

[permalinks]
posts = "/:year/:month/:slug"

# Custom RSS output file matching feed.xml
[outputFormats.RSS]
baseName = "feed"

[outputs]
section = []

[markup.goldmark.renderer]
# Allow HTML mixed within Markdown: https://gohugo.io/configuration/markup/#rendererunsafe
unsafe = true

[params]
subtitle = 'Ask yourself: "What am I doing here?"'
author = "Nils Breunese"
